/* Types file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/
/** MarkerRecord */
export interface MarkerRecord {
	id?: string;
	domain?: string;
	title?: string;
	/** Marker position {lat, lng} */
	position: any;
	description?: string;
	address?: string;
	phone?: string;
	/** Marker email */
	email?: string;
	/** Marker website url */
	website?: string;
	enabled?: boolean;
}

export const MarkerRecordKeys = {
	'id': { type: 'string', priv: false },
	'domain': { type: 'string', priv: false },
	'title': { type: 'string', priv: false },
	'position': { type: 'any', priv: false },
	'description': { type: 'string', priv: false },
	'address': { type: 'string', priv: false },
	'phone': { type: 'string', priv: false },
	'email': { type: 'string', priv: false },
	'website': { type: 'string', priv: false },
	'enabled': { type: 'boolean', priv: false },
};

/** Marker */
export interface Marker {
	id?: string;
	/** Marker title */
	title: string;
	/** Marker position {lat, lng} */
	position: any;
	/** Marker full google data */
	full_address?: any[];
	/** Marker description */
	description?: string;
	/** Marker address */
	address?: string;
	/** Marker phone */
	phone?: string;
	/** Marker email */
	email?: string;
	/** Marker website url */
	website?: string;
	enabled?: boolean;
}

export const MarkerKeys = {
	'id': { type: 'string', priv: false },
	'title': { type: 'string', priv: false },
	'position': { type: 'any', priv: false },
	'full_address': { type: 'any[]', priv: false },
	'description': { type: 'string', priv: false },
	'address': { type: 'string', priv: false },
	'phone': { type: 'string', priv: false },
	'email': { type: 'string', priv: false },
	'website': { type: 'string', priv: false },
	'enabled': { type: 'boolean', priv: false },
};

/** MarkerPosition */
export interface MarkerPosition {
	/** Marker latitude */
	lat?: number;
	/** Marker Longitude */
	lng?: number;
}

export const MarkerPositionKeys = {
	'lat': { type: 'number', priv: false },
	'lng': { type: 'number', priv: false },
};

/** MarkerGoogleAddress */
export interface MarkerGoogleAddress {
	telephone?: string;
	address?: string;
	city?: string;
	postal_code?: string;
	province?: string;
	country?: string;
	formatted?: string;
}

export const MarkerGoogleAddressKeys = {
	'telephone': { type: 'string', priv: false },
	'address': { type: 'string', priv: false },
	'city': { type: 'string', priv: false },
	'postal_code': { type: 'string', priv: false },
	'province': { type: 'string', priv: false },
	'country': { type: 'string', priv: false },
	'formatted': { type: 'string', priv: false },
};

